[env]
TERM = "alacritty"

[window]
dynamic_padding = true
decorations = "buttonless"
opacity = 1
option_as_alt = "Both"

[font]
size = 23

[font.normal]
family = "Cica"
style = "Regular"

[font.bold]
family = "Cica"
style = "Bold"

[font.italic]
family = "Cica"
style = "Italic"

[font.bold_italic]
family = "Cica"
style = "Bold Italic"

[colors.primary]
background = "#282828"
foreground = "#dfbf8e"

[colors.cursor]
text = "CellBackground"
cursor = "#ddc7a1"

[colors.normal]
black = "#665c54"
red = "#ea6962"
green = "#a9b665"
yellow = "#e78a4e"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#dfbf8e"

[colors.bright]
black = "#928374"
red = "#ea6962"
green = "#a9b665"
yellow = "#e3a84e"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#dfbf8e"

[selection]
save_to_clipboard = false

[cursor.style]
blinking = "Always"

[shell]
program = "/usr/local/bin/zsh"
args = [
  "-l",
  "-c",
  "/usr/local/bin/tmux a -t 0 || /usr/local/bin/tmux"
]

[mouse]
hide_when_typing = true
