tap "homebrew/bundle"
brew "bat"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "git-delta"
brew "goenv", args: ["HEAD"]
brew "jq"
brew "lazygit"
brew "n"
brew "utf8proc", args: ["HEAD"]
brew "neovim", args: ["HEAD"]
brew "poetry"
brew "pyenv"
brew "pyenv-virtualenv"
brew "rbenv"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "z"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "alacritty"
cask "alfred"
cask "alt-tab"
cask "dropbox"
cask "google-chrome"
cask "karabiner-elements"
cask "obsidian"
cask "the-unarchiver"
cask "vivaldi"
