git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} {{filename}} +{{line}} '
customCommands:
  - key: "C"
    command: "git cz commit"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
