gui:
  showFileTree: false
git:
  branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --'
  paging:
    colorArg: always
    pager: delta --syntax-theme='Solarized (dark)' --paging=never
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
promptToReturnFromSubprocess: false
customCommands:
  - key: 'C'
    command: 'git cz commit'
    context: 'files'
    loadingText: 'opening git-cz commit tool'
    subprocess: true
